# Generated by astrona-cli's release workflow (.github/scripts/homebrew-formula.sh)
# for v0.3.0 — don't edit by hand, the next release overwrites it.
class Astrona < Formula
  desc "Local Kubernetes (kind) and QEMU lab environments: run, grade, tear down"
  homepage "https://github.com/astrona-io/astrona-cli"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.0/astrona-darwin-arm64"
      sha256 "543be003ede1d862721dd7ed6209500c586a34744e872b2d59de26e0598be8c6"
    end
    on_intel do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.0/astrona-darwin-amd64"
      sha256 "24c22dc4ab9ddd113755f788f6e37018fad65bd51e2edeef61f3716dd78cdc69"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.0/astrona-linux-arm64"
      sha256 "e698803725860d8abc611b4597b983eb5c11f1f9b1c1c742a6f485d86b85c170"
    end
    on_intel do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.0/astrona-linux-amd64"
      sha256 "de17f41bd02fe6ea94beb665a9e6308442f5827d1730955e86316d5cef7fbcf0"
    end
  end

  def install
    bin.install Dir["astrona-*"].first => "astrona"
  end

  def caveats
    <<~EOS
      astrona runs labs on kind with Docker or Podman, and uses kubectl;
      `astrona check` lists what's missing and how to install it.
      Upgrade with `brew upgrade astrona` (not `astrona upgrade`).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/astrona --version")
  end
end
