# Generated by astrona-cli's release workflow (.github/scripts/homebrew-formula.sh)
# for v0.3.3 — don't edit by hand, the next release overwrites it.
class Astrona < Formula
  desc "Local Kubernetes (kind) and QEMU lab environments: run, grade, tear down"
  homepage "https://github.com/astrona-io/astrona-cli"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # Required for every kind lab; Docker or Podman (also required) is left to
  # the user — see caveats. qemu, oras and git are only needed by some labs.
  depends_on "kind"
  depends_on "kubernetes-cli"

  on_macos do
    on_arm do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.3/astrona-darwin-arm64"
      sha256 "5e4eca2e870171781d0a7244a786162dfc8c705d142e5f24bf113440c96ad14b"
    end
    on_intel do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.3/astrona-darwin-amd64"
      sha256 "07f60d2e28ba30fe6beb1acd56970d73343e9fbdbf5e468dfe643b265b3d3691"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.3/astrona-linux-arm64"
      sha256 "6b6ddd91cae2232733008ad00ca6231c5913b365a4fdb08a867a56c1093481f5"
    end
    on_intel do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.3/astrona-linux-amd64"
      sha256 "dd1a8f0202db828c2e4a69f7c78a9ffb853b373ca75ba1cf7222fdf08197ceb5"
    end
  end

  def install
    # A bare download isn't executable yet, and astrona runs below to
    # generate its completions and man pages.
    binary = Dir["astrona-*"].first
    chmod 0755, binary
    bin.install binary => "astrona"
    generate_completions_from_executable(bin/"astrona", "completion")
    system bin/"astrona", "docgen", "--man", "--output", buildpath/"man"
    man1.install Dir[buildpath/"man/*.1"]
  end

  def caveats
    <<~EOS
      kind needs a container engine — Docker or Podman:
        brew install podman && podman machine init && podman machine start
      or Docker Desktop. `astrona check` lists anything else that's missing.

      Upgrade with `brew upgrade astrona` (`astrona upgrade` runs it for you).
      `brew uninstall astrona` leaves ~/.astrona (labs, results, approvals);
      destroy running labs first: astrona destroy <lab>
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/astrona --version")
    assert_match "astrona-run", shell_output("man -P cat #{man1}/astrona-run.1")
    assert_match "__start_astrona", (bash_completion/"astrona").read
  end
end
