# Generated by astrona-cli's release workflow (.github/scripts/homebrew-formula.sh)
# for v0.3.1 — don't edit by hand, the next release overwrites it.
class Astrona < Formula
  desc "Local Kubernetes (kind) and QEMU lab environments: run, grade, tear down"
  homepage "https://github.com/astrona-io/astrona-cli"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # Required for every kind lab; Docker or Podman (also required) is left to
  # the user — see caveats. qemu, oras and git are only needed by some labs.
  depends_on "kind"
  depends_on "kubernetes-cli"

  on_macos do
    on_arm do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.1/astrona-darwin-arm64"
      sha256 "6a1e92d3db3ffb99bd83c8dc50b5d11cbc3da8487fb6b66a06829c50a2c96cb0"
    end
    on_intel do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.1/astrona-darwin-amd64"
      sha256 "5bd0414abe9c70ebfeeb8d2e48b9eb0adcf9a11e089306432ed0cb7bbd6bd4cd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.1/astrona-linux-arm64"
      sha256 "cfb647d18ed70b835d4a9e87b64bd554d4813ea5a79ba91863c65400d5e9844c"
    end
    on_intel do
      url "https://github.com/astrona-io/astrona-cli/releases/download/v0.3.1/astrona-linux-amd64"
      sha256 "5252b9a3ecad3f78378e91e99ad1a4c35bac9dc79cbf3737386205f703c7ebec"
    end
  end

  def install
    # A bare download isn't executable yet, and astrona runs below to
    # generate its completions and man pages.
    binary = Dir["astrona-*"].first
    chmod 0755, binary
    bin.install binary => "astrona"
    generate_completions_from_executable(bin/"astrona", "completion")
    system bin/"astrona", "docgen", "--man", "--output", buildpath/"man"
    man1.install Dir[buildpath/"man/*.1"]
  end

  def caveats
    <<~EOS
      kind needs a container engine — Docker or Podman:
        brew install podman && podman machine init && podman machine start
      or Docker Desktop. `astrona check` lists anything else that's missing.

      Upgrade with `brew upgrade astrona` (`astrona upgrade` runs it for you).
      `brew uninstall astrona` leaves ~/.astrona (labs, results, approvals);
      destroy running labs first: astrona destroy <lab>
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/astrona --version")
    assert_match "astrona-run", shell_output("man -P cat #{man1}/astrona-run.1")
    assert_match "__start_astrona", (bash_completion/"astrona").read
  end
end
